version: '3.8'

services:
  glpi:
    image: diouxx/glpi:latest
    container_name: glpi
    ports:
      - "8080:80"
    volumes:
      - ./glpi/files:/var/www/html/files
      - ./glpi/config:/var/www/html/config
      - ./glpi/marketplace:/var/www/html/marketplace
    environment:
      - GLPI_DB_HOST=db
      - GLPI_DB_NAME=glpidb
      - GLPI_DB_USER=glpiuser
      - GLPI_DB_PASSWORD=glpipassword
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.6
    container_name: glpi-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpiuser
      - MYSQL_PASSWORD=glpipassword
    volumes:
      - ./glpi/mysql:/var/lib/mysql
    restart: unless-stopped